"""
Each new term in the Fibonacci sequence is generated by adding the previous two
terms. By starting with 1 and 2, the first 10 terms will be:
1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
"""
def even_fib():
    limit = 4000000
    sum = 0
    a,b = 0,1
    c = b
    while c < limit:
        if c%2 == 0:
            sum += c
        c = a+b
        a,b = b,c
    print sum

if __name__ == '__main__':
    even_fib()